version: "3.6"

services:
  flask:
    container_name: flask-x64
    build:
      dockerfile: Dockerfile
      target: flask
      context: .
      args:
        pub_key: "${pub_key}"
        sub_key: "${sub_key}"
    ports:
      - "5000:5000"
    image: bt-beacon/flask:x64

  locator:
    container_name: locator-x64
    build:
      dockerfile: Dockerfile
      target: locator
      context: .
      args:
        pub_key: "${pub_key}"
        sub_key: "${sub_key}"
    image: bt-beacon/locator:x64