version: '3.6'

services:

  scan:
    env_file:
      - ./production.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pub_key: ${PUB_KEY:?err}
        sub_key: ${SUB_KEY:?err}
      target: scan
    image: bt-beacon/scan:v1

  flask:
    env_file:
      - ./production.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pub_key: ${PUB_KEY:?err}
        sub_key: ${SUB_KEY:?err}
      target: flask
    image: bt-beacon/flask:v1
    ports:
      - "5000:5000"